package com.stefanini.model;
// Generated 07/11/2016 12:05:08 by Hibernate Tools 4.3.1.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Collection;
import java.util.List;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoinfracao generated by hbm2java
 */
@Entity
@Table(name = "tipoinfracao", catalog = "hackaton")
public class Tipoinfracao implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idTipoInfracao;
	private String descricaoTipoInfracao;
	private Double valor;
	
/*	@OneToMany
	@JoinTable(name="tipoinfracao_infracoes",
		joinColumns=@JoinColumn(name="tipoinfracao_idTipoInfracao"),
		inverseJoinColumns=@JoinColumn(name="infracoes_idInfracao")) 
	private Collection<Infracoes> infracoes;*/

/*	@OneToMany(mappedBy="tipoInfracao", cascade = {CascadeType.MERGE})
	private List<Infracoes> infracoes;*/
	
	public Tipoinfracao() {
	}

	public Tipoinfracao(String descricaoTipoInfracao, Double valor) {
		this.descricaoTipoInfracao = descricaoTipoInfracao;
		this.valor = valor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoInfracao", unique = true, nullable = false)
	public Integer getIdTipoInfracao() {
		return this.idTipoInfracao;
	}

	public void setIdTipoInfracao(Integer idTipoInfracao) {
		this.idTipoInfracao = idTipoInfracao;
	}

	@Column(name = "descricaoTipoInfracao", length = 50)
	public String getDescricaoTipoInfracao() {
		return this.descricaoTipoInfracao;
	}

	public void setDescricaoTipoInfracao(String descricaoTipoInfracao) {
		this.descricaoTipoInfracao = descricaoTipoInfracao;
	}

	@Column(name = "valor", precision = 22, scale = 0)
	public Double getValor() {
		return this.valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

}
